// Test generated by RoostGPT for test testReactJan10 using AI Type Open AI and AI Model gpt-4-1106-preview


import React from 'react';
import { render, fireEvent, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import Languages from '../../../components/Languages'; // Correct import path with file extension assumed `.jsx`

describe('Languages Component', () => {
  test('renders without crashing', () => {
    render(<Languages />);
    expect(screen.getByTestId('languages-container')).toBeInTheDocument();
  });

  test('displays languages in descending order of id', () => {
    const { getAllByTestId } = render(<Languages />);
    const languageItems = getAllByTestId('language-item').map(li => li.id);
    const sortedIds = [...languageItems].sort((a, b) => b - a);
    expect(languageItems).toEqual(sortedIds);
  });

  test('toggles scrollability when buttons are clicked', () => {
    render(<Languages />);
    const prevButton = screen.getByTestId('previous-button');
    const nextButton = screen.getByTestId('next-button');
    fireEvent.click(prevButton);
    expect(screen.getByTestId('languages-container')).toHaveClass('scrollable');
    fireEvent.click(nextButton);
    expect(screen.getByTestId('languages-container')).not.toHaveClass('scrollable');
  });

  test('renders all images with correct alt text', () => {
    render(<Languages />);
    expect(screen.getByAltText('Java Logo')).toBeInTheDocument();
    expect(screen.getByAltText('JavaScript Logo')).toBeInTheDocument();
    expect(screen.getByAltText('PHP Logo')).toBeInTheDocument();
    expect(screen.getByAltText('React Logo')).toBeInTheDocument();
  });
});

